# Generated by Django 2.1.7 on 2019-02-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0002_auto_20190223_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clues',
            name='question',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
