# Generated by Django 2.1.7 on 2019-02-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0003_auto_20190225_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('team_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
