# Generated by Django 2.1.7 on 2019-02-26 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0004_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 0, 55, 31, 644920), verbose_name='created'),
        ),
    ]
