# Generated by Django 2.1.7 on 2019-02-26 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0006_auto_20190226_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 6, 37, 39, 744726)),
        ),
    ]
