# Generated by Django 2.1.7 on 2019-02-26 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0007_auto_20190226_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clues',
            name='ques_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 13, 33, 52, 506749)),
        ),
        migrations.AlterField(
            model_name='users',
            name='team_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
