# Generated by Django 2.1.7 on 2019-02-26 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0010_auto_20190226_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 20, 50, 21, 247697)),
        ),
    ]
