# Generated by Django 2.1.7 on 2019-02-27 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0013_auto_20190226_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 12, 58, 39, 897353)),
        ),
    ]
