# Generated by Django 2.1.7 on 2019-02-27 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0015_auto_20190227_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 13, 4, 13, 106294)),
        ),
    ]
