# Generated by Django 2.1.7 on 2019-03-15 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0016_auto_20190227_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 15, 49, 19, 422709)),
        ),
    ]
