# Generated by Django 2.1.7 on 2019-03-16 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0017_auto_20190315_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clues',
            name='question',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 13, 41, 47, 360846)),
        ),
    ]
