# Generated by Django 2.1.7 on 2019-03-16 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0018_auto_20190316_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clues',
            name='ans',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clues',
            name='prev_ans',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 13, 43, 48, 64439)),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
